name: Continuous Data Generation

concurrency:
  group: datagen-job
  cancel-in-progress: false

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes
  workflow_dispatch:

jobs:
  datagen:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # max 6 hours

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y make

      - name: Run datagen
        run: make datagen
