name: Daily Data Generation

on:
  schedule:
    - cron: '20 7 * * *'  # Runs daily at 07:20 UTC
  workflow_dispatch:      # Optional: allow manual trigger

jobs:
  datagen:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # Max runtime = 6 hours

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y make

      - name: Run datagen
        run: make datagen
